### PR TITLE
If-Else Major functionality

### PR DESCRIPTION
**Pull request by Monik09**

### CODE REVIEW

**Review by vidit2512 — COMMENTED** [review]
lgtm.
there should be some  changes to be done in core.java and Input.java which will be done by chirag.

**Comment by Monik09** [comment]
actually testing is in procedure. it will not be right to merge it now. @vidit2512

**Comment by Monik09** [comment]
Reverting the merge.....

**Comment by Monik09** [comment]
Once the testing is completed, we will merge this

**Comment by Monik09** [comment]
So waiting for testing

**Pull request merged**
