### PR TITLE
Core2

### PR DESCRIPTION
**Pull request by Chirag-Mathur**

### CODE REVIEW

**Comment by Chirag-Mathur** [comment]
This is the working code
But it is showing conflicts.
@Monik09 Please try to look in the matter.

**Comment by Monik09** [comment]
@Chirag-Mathur i have removed the conflicts.

**Comment by Chirag-Mathur** [comment]
@Monik09 Please make sure that Testcode.txt file gives the correct output.

**Comment by Monik09** [comment]
@Chirag-Mathur i dont think there are any conflicts now. you can test your code just for confirmation before merging.

**Pull request merged**
